### ISSUE TITLE
ShulkerBoxPreview  incompatibility

### ISSUE THREAD

**Issue by Nitroito** [yanggx98/Immersive-Tooltip#2]
Minecraft Version: 1.20.6
Fabic Loader: 0.15.11
Fabric API: 0.98.0

Incompatible with ShulkerBoxPreview MOD
i believe is related to Kaleido Lib

Regards

**Comment by yanggx98** [comment]
I can't found 'ShulkerBoxPreview' MOD.Can you give me a link?

**Comment by UltimatChamp** [comment]
I think they are referring to [Shulker Box Tooltip](https://modrinth.com/mod/shulkerboxtooltip).

**Comment by yanggx98** [comment]
> I think they are referring to [Shulker Box Tooltip](https://modrinth.com/mod/shulkerboxtooltip).
  OK,I will try to be compatible with these mods.But I want to implement these feature in my mod.Before long.

**Comment by yanggx98** [comment]
The new version was compatibility:)

**Comment by Nitroito** [comment]
> I think they are referring to [Shulker Box Tooltip](https://modrinth.com/mod/shulkerboxtooltip).

yes.. Shulker Box Tooltip... i am sorry for the missunderstanding
