### ISSUE TITLE
Config system to enable/disable features

### ISSUE THREAD

**Issue by UltimatChamp** [yanggx98/Immersive-Tooltip#4]
I will personally recommend:
- [MidnightLib](https://modrinth.com/mod/midnightlib) _(simple to use and better config ui)_
- [YetAnotherConfigLib](https://modrinth.com/mod/yacl) _(better config ui)_
- [Cloth Config API](https://modrinth.com/mod/cloth-config) _(good old config api)_

**Comment by yanggx98** [comment]
Thanks.I also want to add configuration in this mod. At present, there are too few options that can be configured.

**Comment by Shodelat** [comment]
> Thanks.I also want to add configuration in this mod. At present, there are too few options that can be configured.

I am begging you for an opportunity to turn off armorstand preview. It kinda breaks armortip mod as you can see on screenshot
![image](https://github.com/yanggx98/Immersive-Tooltip/assets/160461810/cd3cca48-8fe3-4831-a40e-782cc39cd359)

**Comment by venaminecraft** [comment]
Any update on this @yanggx98? 😄

**Comment by D-Maxwell** [comment]
This would be greatly appreciated.

**Comment by yanggx98** [comment]
> 对此有任何更新吗？😄
recent time

**Comment by yanggx98** [comment]
> 对此有任何更新吗？😄

it will be updated recently

**Comment by yanggx98** [comment]
In the newest version.it can be set in the config/immersive-tooltip-client.toml file.

**Comment by venaminecraft** [comment]
Awesome, thank you!

**Comment by Shodelat** [comment]
> In the newest version.it can be set in the config/immersive-tooltip-client.toml file.

god blesses u
