### ISSUE TITLE
Hovering over certain items crashes the game (Fabric 1.21)

### ISSUE THREAD

**Issue by kettle4boilin** [yanggx98/Immersive-Tooltip#6]
Crash in Fabric 1.21

There is a crash when hovering over bundles (and some select other items).

This is due to Kaleido (crash happens with just it and not I:T).

Kaleido doesn't have a github I could find, so I'm posting here.

Crash Report:
https://pastebin.com/GHQDb89P

Log File:
https://pastebin.com/5wYwvyTh

**Comment by KillerusIGN** [comment]
I experienced this too- i didn't know what on earth was crashing my game randomly and i blamed c2me for a moment

**Comment by yanggx98** [comment]
Thx. I have fixed it.The next version will be uploaded soon.Please update version 1.1.4 of kaleido.
