### ISSUE TITLE
Crashes when hovering over food when using AppleSkin and Kaleido at the same time.

### ISSUE THREAD

**Issue by KozukiYOMA** [yanggx98/Immersive-Tooltip#8]
I also submitted this to AppleSkin.
This is a Kaleido issue.
When using AppleSkin and Kaleido together, it crashes when hovering over food.
Crashes even if only Immersive tooltip is disabled.
CrashLog
[crash-2024-06-24_18.19.24-client.txt](https://github.com/user-attachments/files/15953222/crash-2024-06-24_18.19.24-client.txt)

Fabric 0.15.11-1.21.0 FabricAPI 0.100.3

**Comment by yanggx98** [comment]
Thx. I have fixed it.The next version will be uploaded soon.Please update version 1.1.4 of kaleido.
